version: "3"

services:
    web:
        build: .
        environment:
          - FLASK_APP=basicRestMethods
          - DB_HOST=mongodb
          - DB_USER=root
          - DB_PASSWORD=123456
          - DB_NAME=test_db
          - DB_PORT=27017
        ports:
          - 5000:5000
        volumes:
          - .:/server
        depends_on:
          - mongodb
            
    mongodb:
        image: mongo:5.0.2
        restart: unless-stopped
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=123456
        ports:
          - 7017:27017
        volumes:
          - db:/data/db
        
volumes:
  db: